### PR TITLE
[WIP] Auth Upgrade

### PR DESCRIPTION
**Pull request by jaxoncreed**

### CODE REVIEW

**Comment by michielbdejong** [comment]
Cool! I'll try it out

**Comment by michielbdejong** [comment]
It seems that `npm run build` is failing on this branch but not on the main branch?

**Comment by michielbdejong** [comment]
I tried `npm ci && npm run build && npm start` and then visit http://localhost:8080 and I see no UI showing up, but instead see this error in the browser developer tools console:
```js
Uncaught (in promise) TypeError: Cannot read property 'handleIncomingRedirect' of undefined
    at _callee$ (index.ts:28)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
```

**Comment by bourgeoa** [comment]
@michielbdejong
auth-upgradede merged to main and apparently working.
There was a changes due to upgrading dependencies.

**Pull request merged**
